ZSH=$HOME/.oh-my-zsh

ZSH_THEME="naive"

plugins=(git github brew chruby ruby rails gem bundler rake pow powify osx vagrant lein z rustup)

source $ZSH/oh-my-zsh.sh

# Load custom configurations
if [ -d $HOME/.config/zsh/ ]; then
  if [ "$(ls -A $HOME/.config/zsh/)" ]; then
    for config_file ($HOME/.config/zsh/*.zsh) source $config_file
  fi
fi
